### ISSUE TITLE
feat: appspec.yml-free, deployment-tool-agnostic deployment trigger

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/kodedeploy#1]
As a lazy developer who wants to automate continuous deployment of myapp to Kubernetes clusters, while not wanting to spend much time on learning yet another deployment tool(s), I want an easy way to turn any deployment command to CodeDeploy-ready.

## How it should work

You just prefix your deployment command with `kodedeploy FLAGS --` and CodeDeploy persists and (re)plays your command whenever necessary.

More concretely, once you run `kodedeploy -- CMD`, it creates:

- A CodeDeploy application (if missing)
- A CodeDeploy revision for the application
- A CodeDeploy deployment group (if missing)
- A CodeDeploy deployment in the group

Each revision is stored inside a S3 bucket, containing following files:

- An auto-generated appspec.yml, before-install.sh, and after-install.sh
- Everything inside the current working directory, so that it can be used from within the CodeDeploy deployment script

`appspec.yml`:

```
version: 0.0
os: linux
files:
  - source: deploy
    destination: /deploy
hooks:
  BeforeInstall:
  - location: codedeploy/before-install.sh
    timeout: 180
  AfterInstall:
  - location: codedeploy/after-install.sh
    timeout: 180
```

`before-install.sh`:

```
#!/usr/bin/env bash

rm -rf /deploy
```

`after-install.sh`:

```
#!/usr/bin/env bash

set -vx

wd="/opt/codedeploy-agent/deployment-root/${DEPLOYMENT_GROUP_ID}/${DEPLOYMENT_ID}/deployment-archive"
image="quay.io/roboll/helmfile:v0.40.1"

# To use kodedeploy pod's serviceaccount to access Kubernetes API
sd="/var/run/secrets/kubernetes.io/serviceaccount/"

cmd="<CMD>"

docker run -v "${wd}:${wd}" -v "${sd}:${sd}" --rm "${image}" -w "${wd}" bash -c "${cmd}"
```

### With kubectl

```console
$ kodedeploy apply --namespace myapp --environment preview -- kubectl apply -n myapp -f deploy/kubernetes
```

### With helm

```console
$ kodedeploy apply --namespace myapp --environment preview -- helm upgrade charts/myapp --name myapp --tiller-namespace myapp --namespace myapp
```

### With helm-tiller

```console
$ kodedeploy apply --namespace myapp --environment preview -- helm tiller run myapp -- upgrade charts/myapp --name myapp --namespace myapp
```
